apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: demo
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      port: 8080 # cluster service port
      targetPort: 8080 # containerPort in the pod
      nodePort: 30081 # node port on minikube VM (free, high port)
